Wandercraft/jiminy

- CMakeLists.txt
- build_tools/cmake/base.cmake
- core/include/jiminy/core/Engine.h
- core/include/jiminy/core/Model.h
- core/src/Engine.cc
- core/src/Model.cc
- examples/double_pendulum/src/double_pendulum.cc
- examples/double_pendulum_py/test_simulation.py
- examples/simple_pendulum_py/test_simulation.py
- gym_jiminy/setup.py
- python/jiminy_py/setup.py
- unit/EngineSanityCheck.cc
- Add option to log internal stepper steps.
- Add options to user-define torque limits.
- Clear integrator code and step method.
- Fix bug with approx divisibility check of sensor/controller update periods.
> Add options and code cleanup

- CMakeLists.txt
- core/include/jiminy/core/Model.h
- core/src/AbstractController.cc
- core/src/Engine.cc
- core/src/Model.cc
- gym_jiminy/setup.py
- python/jiminy_py/setup.py
- python/jiminy_py/src/jiminy_py/simulator.py
- python/jiminy_pywrap/include/jiminy/python/Jiminy.h
> Replace unordered_map by vector

- CMakeLists.txt
- build_tools/setup.sh
- gym_jiminy/setup.py
- python/jiminy_py/setup.py
Update setup.sh to enable Python import of openrobot libraries without using PYTHONPATH.
> Improve setup.py script.

- .github/workflows/linux.yml
- .github/workflows/win.yml
- CMakeLists.txt
- build_tools/setup.sh
- core/include/jiminy/core/telemetry/TelemetryRecorder.h
- core/src/io/MemoryDevice.cc
- core/src/telemetry/TelemetryRecorder.cc
- examples/double_pendulum/double_pendulum.cc
- gym_jiminy/setup.py
- python/jiminy_py/setup.py
- soup/CMakeLists.txt
- soup/gtest/CMakeLists.txt
- soup/jsoncpp/CMakeLists.txt
- unit/CMakeLists.txt
- unit/EngineSanityCheck.cc
- unit_py/data/linear_two_masses.urdf
- unit_py/test_double_spring_mass.py
Related to https://github.com/Wandercraft/jiminy/issues/39
Provide the framework to write Python unit testing for Jiminy. 
Implement a first unit test verifying that Jiminy is capable of simulating a double spring mass system with known analytical solution - and that in that context, Jiminy finds the right solution.
> Add Python unit test framework

- .github/workflows/win.yml
- build_tools/cmake/base.cmake
- build_tools/setup.ps1
- build_tools/setup.sh
- core/include/jiminy/core/Constants.h
- core/include/jiminy/core/Engine.h
- core/include/jiminy/core/robot/Robot.h
- core/include/jiminy/core/telemetry/TelemetryRecorder.h
- core/src/Constants.cc
- core/src/Engine.cc
- core/src/robot/Robot.cc
- core/src/telemetry/TelemetryRecorder.cc
- examples/double_pendulum/double_pendulum.cc
- unit_py/data/simple_pendulum.urdf
- unit_py/test_double_spring_mass.py
- unit_py/test_simple_pendulum.py
Related to https://github.com/Wandercraft/jiminy/issues/39
Add python tests to verify the integrity of the physics being simulated on
a pendulum model:
- nonlinear pendulum simulation matches python integration.
- adding rotor inertia has the expected effect of increasing output body inertia.
> [unit_py] Add unit tests on simple pendulum model

- CMakeLists.txt
- build_tools/setup.sh
- core/include/jiminy/core/Constants.h
- core/include/jiminy/core/engine/EngineMultiRobot.h
- core/include/jiminy/core/engine/Steppers.h
- core/src/Constants.cc
- core/src/engine/EngineMultiRobot.cc
- examples/double_pendulum/double_pendulum.cc
- gym_jiminy/setup.py
- python/jiminy_py/setup.py
- python/jiminy_pywrap/include/jiminy/python/Jiminy.h
- unit_py/data/simple_pendulum.urdf
- unit_py/test_simple_pendulum.py
- Better support of impulse of forces: 
- the impulse-momemtum theorem is now validated
- It is possible to register several impulse force occurring at the same time
- Rework time step restoration mechanism to be more efficient and easier to tune
- Several minor bug fixes
> Various improvements

- data/simple_pendulum/simple_pendulum.urdf
- examples/tutorial.ipynb
- python/jiminy_py/src/jiminy_py/viewer.py
Related to #34 
Add a jupyter notebook to show an interactive example of using jiminy and the BasicSimulator class.
Add function in viewer to directly display results of a logfile (without having to manually do the conversion to a state).
> [jiminy_py] Add jupyter notebook tutorial to document basic usage.

- CMakeLists.txt
- python/jiminy_py/src/jiminy_py/viewer.py
Duplicate https://github.com/Wandercraft/jiminy/pull/103
> Fix robot names

- build_tools/build_install_deps_linux.sh
Update to pinocchio v2.4.4 that fixes the support of panda3d viewer
> Manylinux pinocchio update

- INSTALL.md
- README.md
- gym_jiminy/gym_jiminy/examples/tianshou/cartpole_ppo.py
Update documentation and add continuous action cartpole example.
> Tianshou example

- core/include/jiminy/core/engine/EngineMultiRobot.h
- core/src/Utilities.cc
- core/src/engine/EngineMultiRobot.cc
- examples/double_pendulum/double_pendulum.cc
- gym_jiminy/gym_jiminy/common/robots.py
- gym_jiminy/gym_jiminy/examples/tianshou/cartpole_ppo.py
- Add timeout option to engine stepper
- Remove default max number of iterations
> Various fixes

- core/src/robot/BasicSensors.cc
- core/src/robot/Robot.cc
- unit_py/test_simple_pendulum.py
Fix IMU signal computation:
- spatial acceleration was used instead of linear acceleration.
- we were missing one forwardKinematics step.
> Fix imu signal

- CMakeLists.txt
- INSTALL.md
- core/include/jiminy/core/engine/EngineMultiRobot.h
- core/include/jiminy/core/robot/AbstractSensor.tpp
- core/include/jiminy/core/robot/BasicSensors.h
- core/include/jiminy/core/robot/FixedFrameConstraint.h
- core/include/jiminy/core/robot/Robot.h
- core/src/Utilities.cc
- core/src/engine/EngineMultiRobot.cc
- core/src/robot/BasicSensors.cc
- core/src/robot/Robot.cc
- examples/double_pendulum/double_pendulum.cc
- gym_jiminy/gym_jiminy/common/robots.py
- gym_jiminy/gym_jiminy/examples/tianshou/cartpole_ppo.py
- python/jiminy_pywrap/include/jiminy/python/Jiminy.h
- python/jiminy_pywrap/include/jiminy/python/Utilities.h
- unit_py/test_simple_pendulum.py
- [core] Better support of shared array between Python/C++ (including bug fix)
- [core] Fix bug in drift computation for fixed body constraints 
- [core] Add timeout option to the engine stepper
- [core] Add frame placement computation
- [core] Fix sensor init with delay.
- [core] Specific bias + noise implementation for IMU quaternion: Use IMU rotation for bias and small angle hypothesis for the noise, more consistent as true sensor bias.
_________
- [jiminy_py] Enable constructor to SensorData (sharing memory with Python)
_________
- [unit] Add unit test for sensors: both raw measurement, and noise / bias / delay
_________
- [doc] Update installation instructions
> Release 1.3.37

- gym_jiminy/gym_jiminy/common/robots.py
- [gym_jiminy] Add a new _setup_environment method to the generic gym robot environment. This method can be overloaded, for example to create engine_py itself, which is especially useful for example to generate new robot model at each reset without being hacky.
> Gym robot improvements

- python/jiminy_py/src/jiminy_py/engine_asynchronous.py
- Fix a bug with engine asynchronous initial state
- Improve initialization by providing meaningful initial sensors data
> Improve Engine asynchronous initialization behavior

- CMakeLists.txt
- gym_jiminy/gym_jiminy/common/robots.py
- python/jiminy_py/src/jiminy_py/engine_asynchronous.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [jiminy_py] Fix running gepetto-gui detection bug.
- [jiminy_py] Fix a bug with engine asynchronous initial state
- [jiminy_py] Improve initialization by providing meaningful initial sensors data
____
- [gym_jiminy] Add a new _setup_environment method to the generic gym robot environment.
> Jiminy release 1.3.40

- gym_jiminy/gym_jiminy/common/robots.py
Gym robot now returns pure Python native dictionary for the sensors data, instead of a C++ sensorData object. Yet, this conversion is done by reference, and can be converted back by reference to sensorData using its constructor. So no information is lost, and it is computationally highly efficient.
> Gym robot Python native observation

- gym_jiminy/gym_jiminy/envs/acrobot.py
- gym_jiminy/gym_jiminy/envs/cartpole.py
Some variables have been renamed in base class, without update the derived environments accordingly.
> Fix gym toy environments

- python/jiminy_py/src/jiminy_py/engine_asynchronous.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [jiminy_py] Automatically delete robot when closing. 
- [jiminy_py] Add support of node deletion for meshcat viewer. 
- [jiminy_py] Fix initial pinocchio data for engine async.
> Engine asynchronous improvements

- CMakeLists.txt
- gym_jiminy/gym_jiminy/common/flatten_observation.py
- gym_jiminy/gym_jiminy/common/robots.py
- gym_jiminy/gym_jiminy/envs/acrobot.py
- gym_jiminy/gym_jiminy/envs/cartpole.py
- gym_jiminy/gym_jiminy/examples/tianshou/cartpole_ppo.py
- python/jiminy_py/src/jiminy_py/dynamics.py
- python/jiminy_py/src/jiminy_py/engine_asynchronous.py
- python/jiminy_py/src/jiminy_py/simulator.py
- python/jiminy_py/src/jiminy_py/viewer.py
- python/jiminy_pywrap/include/jiminy/python/Jiminy.h
- [jiminy_py] Replace ValueError by RuntimeError when the error is not directly related to argument type or value error
- [jiminy_py] Add new attribute to Viewer to keep track of backend's parent and associated subprocess
- [jiminy_py] EngineAsynchronous only setup the camera pose if it is the backend's parent
- [jiminy_py] Add optional argument 'viewers' to 'play_trajectories' to use existing viewer for display, then return the used ones
- [jiminy_py] Add non static close method to Viewer, that remove the associated robot, and closes backend (only if the instance opened it)
- [jiminy_py] Automatically delete robot when closing. 
________________
- [gym_jiminy] Gym robot now returns pure Python native dictionary for the sensors data, instead of a C++ sensorData object
> Jiminy release 1.2.41

- build_tools/cmake/base.cmake
Reverts Wandercraft/jiminy#154
> Revert "Enable ccache automatically if available"

- gym_jiminy/gym_jiminy/common/robots.py
Jiminy is using soft bounds for the joint position and velocity limits. As a result, sensor observations can be slightly out-of-bounds, resulting in assertion failure for learning framework enforcing strict inclusion of observation in observation space. This PR uses absolute margins instead of previously relative, and their values are tuned to be as small as possible, while ensuring that it never gets out of bounds.
> Robust  gym robot observation space limits

- gym_jiminy/gym_jiminy/common/robots.py
- python/jiminy_py/setup.py
- python/jiminy_py/src/jiminy_py/viewer.py
-  Add option to record trajectories in viewer
- Fix robot deletion issue in viewer.
- Increase velocity bounds for gym obs space to make sure it never goes out-of-bounds
> Add record trajectories option

- gym_jiminy/gym_jiminy/common/robots.py
- python/jiminy_py/src/jiminy_py/engine_asynchronous.py
- python/jiminy_py/src/jiminy_py/meshcat/index.html
- python/jiminy_py/src/jiminy_py/viewer.py
- Fix viewer not working in viewer
- Redirect meshcat 'static' url without trailing '/'
- Fix favicon request
- Do not require client for EngineAsync during rendering
> Meshcat viewer fixes and minor improvements

- gym_jiminy/gym_jiminy/common/robots.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [viewer/play_trajectory] Enforce video framerate and file format automatically (50fps, mp4)
- [viewer/play_trajectory] Add video compatibility with HTML5 (can be embedded in markdown...etc)
- [viewer/play_trajectory] Add support of camera traveling for both video recording and "human" mode
Various minor bug fixes.
> [Viewer] Fix and improve video recording

- python/jiminy_py/src/jiminy_py/viewer.py
- Fix video recording not working with Gepetto-gui. 
- Fix logger warning filtering.
> [Viewer] Fix Gepetto-gui support

- gym_jiminy/gym_jiminy/common/robots.py
- python/jiminy_py/src/jiminy_py/meshcat/index.html
- python/jiminy_py/src/jiminy_py/viewer.py
- [python/Viewer] Reduce video recording fps. 
- [python/Viewer] Do not enforce multiprocess spawn on linux. 
- [python/Viewer] Fix meshcat camera using capture_frame.
- [Gym/Robot] Remove 'depth_array' rendering mode since it is not available
> [Gym] Improve video recording

- python/jiminy_py/src/jiminy_py/viewer.py
- Fix viewer relative camera pose. 
- Add relative camera pose configuration during traveling.
> [Viewer] Fix and improve camera travelling.

- python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Add viewer 'attach_camera' method and use it for travelling.
- [Viewer] Remove misused signal handling.
> [Viewer] Fix signal handling and improve camera traveling.

- python/jiminy_py/src/jiminy_py/meshcat/recorder.py
- python/jiminy_py/src/jiminy_py/meshcat/server.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Make meshcat backend recorder performance more reliable
- [Viewer] Reduce video resolution down to 800x800 instead of  1000x1000 to speed-up recording
- [Viewer] Fix meshcat client redirection error when trailing backslash is missing in url
> [Viewer] Minor cleanup and improvement

- python/jiminy_py/src/jiminy_py/meshcat/recorder.py
- python/jiminy_py/src/jiminy_py/meshcat/wrapper.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Make sure that the viewer backend is alive before executing commands (~ 1% overhead only)
- [Viewer] Make sure the backend processes are terminated cleanly in any cases (hopefully!)
- [Viewer] Do NOT close backend automatically when 'close' is called by an instance
> [Viewer] Check method calls

- python/jiminy_py/src/jiminy_py/meshcat/recorder.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Make sure the backend browser is killed at exit. 
- [Viewer] Do NOT catch KeyboardInterrupt anymore.
> [Viewer] Safe exit (for real this time...)

- CMakeLists.txt
- python/jiminy_py/src/jiminy_py/meshcat/wrapper.py
- python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Do not apply the optimized patch for handling kernel shell messages selectively for ipykernel < 5.0
- [Viewer] Fix non-resizeable display window on notebook and wrong initial window size on Google Colab
> [Viewer] Fix support of Google Colab
