Wandercraft/jiminy

CMakeLists.txt, gym_jiminy/setup.py, python/jiminy_py/setup.py, python/jiminy_pywrap/include/jiminy/python/Jiminy.h
It also allows to install any version of jiminy-py with gym-jiminy having the same minor version tag.
=> Add Python bindings for set/get motor options.

CMakeLists.txt, core/include/jiminy/core/AbstractController.h, core/include/jiminy/core/AbstractSensor.tpp, core/include/jiminy/core/Engine.h, core/include/jiminy/core/TelemetryRecorder.h, core/src/AbstractController.cc, core/src/Engine.cc, core/src/TelemetryRecorder.cc, core/src/Utilities.cc, gym_jiminy/setup.py, python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/viewer.py, python/jiminy_pywrap/include/jiminy/python/Jiminy.h
This MR fixes various bugs in the simulation leading to poor computational efficiency because of very small internal step size, and wrong acceleration estimation during the projection on the state space.
- No alterating of the stepper state during the update of the telemetry
- Full precision (double) while parsing the data log file (note that the time accuracy is 1us by design)
- Catch the exception raised by the viewer if Gepetto-viewer is closed during a replay, so that it stops the animation without error.
=> Fix various flaws

CMakeLists.txt, gym_jiminy/setup.py, python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/__init__.py, python/jiminy_py/src/jiminy_py/log.py, python/jiminy_py/src/jiminy_py/plotter.py, python/jiminy_pywrap/include/jiminy/python/Jiminy.h
To make jiminy even nicer to use, this PR proposes a simple python tool, `jiminy_plot`, to plot the content of a logfile rapidly using matplotlib. Below is an example of rendering (actual data is meaningless):
```
jiminy_plot  /tmp/example_sagittal.data H*.c*Pos*Body:H*.c*Vel*Body H*.energy
```
=> [python] Add generic plotting tool for jiminy logs.

CMakeLists.txt, build_tools/cmake/base.cmake, build_tools/cmake/buildPythonWheel.cmake, core/src/robot/FixedFrameConstraint.cc, gym_jiminy/setup.py, python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/__init__.py, python/jiminy_py/src/jiminy_py/plotter.py, python/jiminy_py/src/jiminy_py/viewer.py
One of the main purpose I use jiminy for is to compare two simulations of the same system, with different parameters. In that context, I get two log files, with the same content (in terms of logged fields) and length.
This PR adds the capacity for ```jiminy_plotter``` to compare two or more logs, by plotting them on the same graph:
```jiminy_plotter logfile.data regex -c the_logs_I_want_to_compare_to.data```
Feature preview:
=> [jiminy_py] Add option for plotter to compare several logfiles.

build_tools/build_install_deps_linux.sh, core/src/engine/EngineMultiRobot.cc, gym_jiminy/gym_jiminy/envs/acrobot.py, gym_jiminy/gym_jiminy/envs/cartpole.py, python/jiminy_py/src/jiminy_py/__init__.py, python/jiminy_py/src/jiminy_py/engine_asynchronous.py, python/jiminy_py/src/jiminy_py/viewer.py
- Fix jiminy_py import failing on windows
- Fix rare issue where the viewer detects that a gepetto client is already opened even though it is not (or is not responding to requests)
- Enable to specify a custom controller to the constructor of EngineAsynchronous
=> Various minor improvements.

core/include/jiminy/core/Constants.h, core/include/jiminy/core/engine/EngineMultiRobot.h, core/include/jiminy/core/telemetry/TelemetryData.h, core/include/jiminy/core/telemetry/TelemetryRecorder.h, core/src/Constants.cc, core/src/engine/EngineMultiRobot.cc, core/src/telemetry/TelemetryRecorder.cc
Add `Global.TIME_UNIT` constant to specify the unit in which time is logged, this enables the user to change the precision with which logging is done.
=> [jiminy] Allow change in the unit used to log the simulation.

core/src/robot/Robot.cc, python/jiminy_pywrap/include/jiminy/python/Jiminy.h, python/jiminy_pywrap/include/jiminy/python/Utilities.h
- Better support of shared array between Python/C++ 
(including bug fix related to undesired memory copy).
- Add SensorData Python constructor : The resulting C++ object is sharing memory with Python.
- Add `__repr__` method to SensorData.
- Improve efficiency of sensor data `__getitem__` method when using only sensor type as key.
=> Add SensorData Python constructor

core/include/jiminy/core/robot/FixedFrameConstraint.h, core/include/jiminy/core/robot/Robot.h, core/src/robot/Robot.cc
Drift was not computed correctly: the full body acceleration was used instead of the drift.
Fix: add a forwardKinematic pass with zero joint acceleration to compute the drift.
=> Fix bug in drift computation for fixed body constraints.

core/include/jiminy/core/robot/AbstractSensor.tpp, core/include/jiminy/core/robot/BasicSensors.h, core/src/robot/BasicSensors.cc, unit_py/test_simple_pendulum.py
- Properly sensor initialization in case of delay
- Implement more realistic bias/noise for IMU quaternion since it does not make sense to use simple additive noise/bias with 4 independent coefficients
- Check the size of the user-specified bias and std at setOptions level for the IMU
- Add unit test for sensor skew measurement
=> Sensor skew measurement rework

core/src/robot/Model.cc
Pinocchio data associated with the rigid model was not initialized, and the center of mass was not computed for both rigid and flexible model. Yet, computing it at least once is required to initialize some essential stuffs such as the mass of each bodies.
=> Better initialization of pinocchio data (rigid+flexible)

gym_jiminy/gym_jiminy/envs/acrobot.py, gym_jiminy/gym_jiminy/envs/cartpole.py
- Use new `_setup_environment` method to configure the robot/engine options of the provided toy environments, which has been design exactly for that kind of stuff, instead of `__init__` as it was previously the case. Doing this, one can reliably derive those environment to customize them without compromising the default configuration.
=> Update the example gym envs

gym_jiminy/gym_jiminy/common/flatten_observation.py, gym_jiminy/gym_jiminy/common/robots.py, gym_jiminy/gym_jiminy/examples/tianshou/cartpole_ppo.py, python/jiminy_py/src/jiminy_py/engine_asynchronous.py, python/jiminy_pywrap/include/jiminy/python/Jiminy.h
In addition, Gym generic robot environment know returns flatten sensor data by default since it is more efficient to access individual sensor data using numpy array slicing than using dictionary keys.
=> Fix sensorDataMap_t Python wrapper not sharing constructor Python dict lifetime

python/jiminy_py/src/jiminy_py/dynamics.py, python/jiminy_py/src/jiminy_py/engine_asynchronous.py, python/jiminy_py/src/jiminy_py/simulator.py, python/jiminy_py/src/jiminy_py/viewer.py
- Replace ValueError by RuntimeError when the error is not directly related to argument type or value error
- Add new attribute to Viewer to keep track of backend's parent and associated subprocess
- EngineAsynchronous only setup the camera pose if it is the backend's parent
- Add optional argument 'viewers' to 'play_trajectories' to use existing viewer for display, then return the used ones
- Add non static close method to Viewer, that closes backend only if the instance opened it
=> Minor improvements

core/include/jiminy/core/Utilities.h, core/include/jiminy/core/engine/EngineMultiRobot.h, core/src/Utilities.cc, core/src/control/AbstractController.cc, core/src/engine/EngineMultiRobot.cc, python/jiminy_py/MANIFEST.in, unit_py/data/point_mass.urdf, unit_py/test_double_spring_mass.py, unit_py/test_point_mass.py
The formula for handling external torques was wrong due to misunderstanding between local, global and world frame: this has been clarified.
Force sensors returned values in the world frame instead of their sensor frame.
Added unit test of both of these features.
_____________________
It also fixes an issue with quaternion integration slowly diverging from SE3 over time by "normalizing" the configuration vector before and after each internal stepper step.
=> Fix application of external torques

python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/viewer.py
- Enable to connect to any existing zmq meshcat server hosted locally on any port
- Proper initial mesh position at Viewer initialization
- Add small delay to avoid viewer "race condition" at the beginning of replay after loading meshes
- Add timeout for lock acquisition for parrallel rendering
- Better handling of exceptions and closing
=> Meshcat connect

python/jiminy_py/src/jiminy_py/viewer.py
- [jiminy_py/Viewer] Remove restriction of `refresh` method to `use_theoretical_model = False`. Incidentally, it fixes  exception raising at init for `use_theoretical_model = False`
- [jiminy_py/Viewer] Fix bug opening new navigator window even if `is_backend_parent = False` for `meshcat` backend
=> Fix meshcat behavior.

python/jiminy_py/src/jiminy_py/viewer.py
- Fix detection of meshcat server executed using `meshcat-server` executable script (Python "entry-point").
=> Robust detection of running meshcat server

CMakeLists.txt, build_tools/cmake/base.cmake, python/jiminy_py/src/jiminy_py/viewer.py
- [jiminy_py/Viewer] Remove restriction of `refresh` method to `use_theoretical_model = False`. Incidentally, it fixes  exception raising at init for `use_theoretical_model = False`
- [jiminy_py/Viewer] Fix bug opening new navigator window even if `is_backend_parent = False` for `meshcat` backend
- [jiminy_py/Viewer] Fix detection of meshcat server executed using `meshcat-server` executable script (Python "entry-point").
=> Jiminy release 1.2.43

gym_jiminy/gym_jiminy/common/robots.py
The joint positions and velocities can still be out-of-bounds for ridiculous command.
=> Increase gym robot joint margins to fix out-of-bounds

python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/engine_asynchronous.py, python/jiminy_py/src/jiminy_py/meshcat/index.html, python/jiminy_py/src/jiminy_py/meshcat/recorder.py, python/jiminy_py/src/jiminy_py/meshcat/server.py, python/jiminy_py/src/jiminy_py/viewer.py
- [jiminy_py/viewer] Enable capture frame on Windows and in Jupyter notebook using background process and IPC.
- [jiminy_py/viewer] Add option to disable viewer automatic gui opening at viewer backend startup. 
- [jiminy_py/viewer] video recording options of 'play_trajectory'  have been merged in a single one.
- [jiminy_py/viewer] Do not throw error but warning if 'wait' is not available. 
- [jiminy_py/viewer] Do not kill meshcat server and recorder when SIGINT signal is emitted. 
- [jiminy_py/viewer] Make sure multiprocessing IPC managers are properly closed when viewer is closed.
- [jiminy_py/viewer] Improve running meshcat server detection.
- [jiminy_py/viewer] Improve default meshcat initial camera pose. 
- [jiminy_py/viewer] Fix capture frame not waiting for mesh loading.
- …
=> [jiminy_py] Fix support of capture_frame on Windows and Jupyter.

python/jiminy_py/src/jiminy_py/meshcat/index.html, python/jiminy_py/src/jiminy_py/meshcat/recorder.py, python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Capture frame using Meshcat in ".webp" format instead of ".png" to improve efficiency
- [Viewer] Minor performance improvement of backend recorder thread by avoiding useless rendering operations
=> [Viewer] Improve meshcat capture frame efficiency

python/jiminy_py/src/jiminy_py/meshcat/index.html, python/jiminy_py/src/jiminy_py/meshcat/recorder.py, python/jiminy_py/src/jiminy_py/meshcat/server.py, python/jiminy_py/src/jiminy_py/meshcat/webm-writer-0.3.0.js, python/jiminy_py/src/jiminy_py/meshcat/wrapper.py, python/jiminy_py/src/jiminy_py/viewer.py
New features and improvements:
- [Viewer] 'wait' methods no longer requires being parent of meshcat server
- [Viewer] Add dedicate meshcat wrapper which handles video recording directly in javascript.
- [Viewer] Dramatically improve recording speed using meshcat from 2FPS to 12FPS by using for recent Chrome release and using Javascript WebM Writer.
- [Viewer] Bundle WebM Writer to enable setting filename, framerate and quality.
=> [Viewer] Speedup meshcat video recording

python/jiminy_py/src/jiminy_py/meshcat/index.html, python/jiminy_py/src/jiminy_py/meshcat/recorder.py, python/jiminy_py/src/jiminy_py/meshcat/server.py, python/jiminy_py/src/jiminy_py/meshcat/wrapper.py, python/jiminy_py/src/jiminy_py/simulator.py, python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Native and full support of Jupyter, using directly kernel communication to avoid websockets and port forward all together. It should work on Google Colab but it cannot be tested easily (must be installed using wheel)
- [Viewer] Remove the support of port forwarding, since it is not longer relevant
- [Viewer] Create display cell in notebook mode when instantiating a viewer while no display cell is already available
- [Viewer] Check for browser availability when calling 'open_gui', and wait for the client to be ready
- [Viewer] Avoid timeout on low-hand machine while starting video recording
- [Viewer] Improve the reliability of running Meshcat server detection. Remove heartbeat check since it is impossible to estimate appropriate response time (It can take a while if the meshes …
=> [Viewer] Add native support of Jupyter and Google Colab

CMakeLists.txt, python/jiminy_py/setup.py, python/jiminy_py/src/jiminy_py/meshcat/wrapper.py, python/jiminy_py/src/jiminy_py/viewer.py
- [Viewer] Only process kernel comm messages on the spot to avoid messing up . 
- [Viewer] Do not examine Ipython port while looking for ZMQ Meshcat to avoid throwing a low-level kernel exception.
Fix #187 side-effects
=> [Viewer] Fix kernel exception and stack corruption in notebooks

CMakeLists.txt, python/jiminy_py/src/jiminy_py/meshcat/index.html, python/jiminy_py/src/jiminy_py/meshcat/server.py, python/jiminy_py/src/jiminy_py/meshcat/wrapper.py
- [Viewer] Do not rely on knowing the expected comm_id size in byte 
- [Viewer] Handle already closed connections properly.
- [Viewer] Add warning to recommand increasing 'iopub_msg_rate_limit' for notebooks (Done by default on Google Colab)
=> [Viewer] More robust server to frontend forwarding
